name: Docker Image CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --tag stub_container:latest
    - name: Push the Docker Image
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        docker login docker.pkg.github.com -u github-actions -p $GITHUB_TOKEN
        docker tag stub_container:latest docker.pkg.github.com/0gajun/stub_container/stub_container:latest
        docker push docker.pkg.github.com/0gajun/stub_container/stub_container:latest
